#数据源
spring:
  profiles:
    active: rabbitmq

  datasource:
    username: root
    password: lx19960430
    url: jdbc:mysql://localhost:3306/medical?characterEncoding=utf-8&useSSL=false
    type: org.apache.tomcat.jdbc.pool.DataSource
#    type: com.alibaba.druid.pool.DruidDataSource

  #thymeleaf缓存
  thymeleaf:
    cache: false

#Redis缓存
  redis:
    host: localhost
    port: 6379

  #Spring-mail配置
  mail:
    username: 792789101@qq.com
    password: tdtqvzspibfpbfhj
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  #热部署
  devtools:
    livereload:
      enabled: true

  #RabbitMQ
  rabbitmq:
    #host: 192.168.0.109
    #host: 192.168.180.9
    host: 106.14.160.207
    port: 5672
    username: guest
    password: guest
    #手动确认接收消息
    listener:
      simple:
        acknowledge-mode: manual

#server配置
server:
  context-path: /medical
  session:
    timeout: -1

#浏览器cookie时间，单位秒
#server.session.cookie.max-age=600

#mybatis系列文件配置
#驼峰命名规则
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smxy.healthmedical.bean
  configuration:
    map-underscore-to-camel-case: true

#pagehelper配置
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
  reasonable: true
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  support-methods-arguments: false

#日志
#logback 配置
logging:
  level:
    com.smxy.healthmedical.controller.BackStageController.addPageViews: debug
  file: D:/IDEA Case/medical-hadoop.log
  path: /log/medical-hadoop

